theme = "hugo-split-theme"
baseURL = 'https://councilsofthefuture.org/'
languageCode = 'en-us'
title = 'Councils of the Future'
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"] #remove section disable

# Local preview mode
relativeURLs = true
uglyURLs = false

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2022 Councils of the Future"

[params]

  # Metadata for search engines and social sharing
  author = "Councils of the Future"
  description = "in the interest of the present."
  
  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/rand_sketch_rev_white_black_bg.png"
      position = "center center"


  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Listen"

      [[params.links.list1.link]]
        text = "soundcloud"
        url = "https://soundcloud.com/councils-of-the-future"

      [[params.links.list1.link]]
        text = "bandcamp"
        url = "https://councilsofthefuture.bandcamp.com"
        
        
      #[[params.links.list1.link]]
      #  text = "musings"
       # url = "/post/"

[privacy] #https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split